### ISSUE TITLE
Mockup Desktop

### ISSUE THREAD

**Issue by jvbfelix** [citi-onboarding/Engaj#2]
Mockup responsável por representar a visualização dosite na versão desktop

**Comment by jrmmendes** [comment]
Pedidos do cliente:
- [ ] Mudar fonte para a padrão da Engaj
- [ ] Testar o fundo verde e usar a logo correta no `footer`

**Comment by lucaszsd** [comment]
Acabei de fazer as alterações pedidas pelo cliente. Upei no drive o mockup com a fonte alterada, e algumas opções de footer, a original e algumas opções usando as cores da EJ
