### ISSUE TITLE
Tornar footer dinâmico

### ISSUE THREAD

**Issue by jvbfelix** [citi-onboarding/Engaj#49]
Esta issue visa tornar os campos do footer dinâmicos

**Comment by jrmmendes** [comment]
@jvbfelix fiz isso que tu pediu e também coloquei o email pra ser clicável (via protocolo mailto). Outra coisa que acabei corrigindo é pro link do maps ser dinâmico e adicionando valores padrão para todos os campos (ajuda o futuro usuário a ter noção sobre como colocar)
